name: Go Code Review

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  go-code-review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Install dependencies
      run: go mod download

    - name: ChatGPT code review
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
      run: |
        response=$(curl -X POST -H "Authorization: Bearer $CHATGPT_API_KEY" -H "Content-Type: application/json" -d '{"code": "'$(cat main.go)'", "language": "go"}' https://api.chatgpt.com/review)
        review=$(echo $response | jq -r '.review')
        body="ChatGPT code review:\n$review"
        url=$(jq -r '.pull_request.url' $GITHUB_EVENT_PATH)
        number=$(jq -r '.pull_request.number' $GITHUB_EVENT_PATH)
        comments_url="$url/comments"
        payload=$(echo '{}' | jq --arg body "$body" --arg comments_url "$comments_url" '.body = $body | .comments_url = $comments_url')
        curl -X POST -H "Authorization: token $GITHUB_TOKEN" -d "$payload" "$comments_url"
