name: Go Code Review with ChatGPT

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install dependencies
        run: go mod download

      - name: Build and Test Code
        run: |
          go build ./...
          go test ./...

      - name: Generate Code Coverage Report
        run: |
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out > coverage.txt

      - name: Request Code Review
        id: code-review
        uses: peter-evans/create-issue-from-file@v2
        with:
          title: "Code Review Request"
          body: |
            Please review the code changes in this pull request.

            @ChatGPT can you review this code and give feedback on any issues or improvements?

            Pull Request: ${{ github.event.pull_request.html_url }}

            Changes:
            $(git diff --name-only ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }})

            Code Coverage Report:
            $(cat coverage.txt)
          assignees: ChatGPT

      - name: Wait for ChatGPT to complete review
        uses: octokit/wait-for-issue-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ steps.code-review.outputs.issue-number }}
          check-interval: 30
          timeout: 600

      - name: Get review comment from ChatGPT
        id: review-comment
        uses: octokit/request-action@v2.x
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          route: GET /repos/:owner/:repo/issues/:issue_number/comments
          owner: ${{ github.repository_owner }}
          repo: ${{ github.repository }}
          issue_number: ${{ steps.code-review.outputs.issue-number }}

      - name: Post review comment to PR
        uses: actions/github-script@v4.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = ${{ toJSON(fromJsonString(steps.review-comment.outputs.data).find(c => c.user.login === 'ChatGPT')) }};
            if (comment) {
              github.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `Review from ChatGPT: ${comment.body}`
              });
            } else {
              console.log('No comment from ChatGPT');
            }
